version: '2'

services:
  
  br-endereco:
    container_name: br-endereco
    build: 
      context: .
      dockerfile: OpenBr.Endereco.Web.Api/Dockerfile
    ports: 
      - "5000:80"
    environment:  
      - ConnectionStrings:MongoDb=mongodb://admin:admin@mongoBrEndereco:27017/endereco?authSource=admin&readPreference=primary&ssl=false
      - HealthChecksUI:HealthChecks:0:Uri=http://localhost/selfcheck
    depends_on: 
      - "mongoBrEndereco"
    networks: 
      - net-br-endereco
      
  br-worker:
    container_name: br-worker
    build: 
      context: .
      dockerfile: OpenBr.Endereco.Worker/Dockerfile
    environment:  
      - ConnectionStrings:MongoDb=mongodb://admin:admin@mongoBrEndereco:27017/endereco?authSource=admin&readPreference=primary&ssl=false
      - Scheduler:Cron=15 4 * * *
    depends_on: 
      - "mongoBrEndereco"
    networks: 
      - net-br-endereco

  mongoBrEndereco:
    container_name: mongoBrEndereco
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: admin
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    networks: 
      - net-br-endereco

networks: 
  net-br-endereco:
    driver: bridge